name: Labeler

on:
  pull_request_target:
  issues:

# Declare default permissions as read only.
permissions: read-all

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v5.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true
