name: Labeler

on:
  pull_request_target:

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/labeler@6463cdb00ee92c05bec55dffc4e1fce250301945 # v5.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true
