name: Greetings

on:
  pull_request_target:
  issues:

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Thanks for taking the time to raise awareness of an issue you have found in our software!
          pr-message: |
            Congratulations on raising your first pull request!
            We appreciate your contribution and look forward to reviewing your contribution.
            In the meantime, please review our [contributing guidelines](https://github.com/${{ github.repository }}/blob/main/CONTRIBUTING.md).
