name: Labeler

on:
  pull_request_target:
  issues:

# Declare default permissions as read only.
permissions: read-all

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - uses: actions/labeler@b0a1180683c9f17424de4d71c044bea4c7b9bc7c # v5.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true
