name: Labeler

on:
  pull_request_target:
  issues:

# Declare default permissions as read only.
permissions: read-all

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - uses: actions/labeler@110d44140c9195b853f2f24044bbfed8f4968efb # v5.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true
