name: Validate

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Format
        run: go fmt ./...

      - name: Lint
        run: go vet ./...

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -o ./bin/ -v ./...

      - name: Test
        run: go test -v ./...

      - name: Coverage
        run: go test -coverprofile=coverage.out ./...

      - name: Coverage Report
        run: go tool cover -html=coverage.out -o coverage.html
