name: Create Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v4
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@dca8468d37b6d090cde2c7b97b738a37134f5ffb # v5.4.0
        with:
          go-version: "1.24"

      - name: Build
        run: go build -o ./bin/ ./...

      - name: Upload Artifact
        uses: actions/upload-artifact@6027e3dd177782cd8ab9af838c04fd81a07f1d47 # v4.6.2
        with:
          name: server_build
          path: bin/
